#!/bin/sh
xrandr --output LVDS1 --off
xrandr --output HDMI3 --off
xrandr --output VGA1 --off
xrandr --output HDMI3 --auto --pos 0x0 --rotate normal 
xrandr --output VGA1 --primary --auto --pos 1920x0 --rotate normal
i3-msg restart
