#!/bin/sh

#########################################################
#Script Name	: dock
#Description	: Loads the monitor settings when getting
#                 docked.
#Args           : None
#Author       	: Luk Schwalb
#Email         	: schwalb@luk.im
#########################################################

xrandr --output LVDS1 --off
xrandr --output HDMI3 --off
xrandr --output VGA1 --off
xrandr --output HDMI3 --auto --pos 0x0 --rotate normal 
xrandr --output VGA1 --primary --auto --pos 1920x0 --rotate normal
i3-msg restart
