#!/bin/bash

#########################################################
#Script Name	: duck
#Description	: Prints a duck walking up and down.
#                 Made for a polybar module.
#Args           : None
#Author       	: Luk Schwalb
#Email         	: schwalb@luk.im
#########################################################

SPACECOUNT=100
SLEEPTIME=0.01
SPACES=""

while [ true ];
do
    for i in $( seq 0 $SPACECOUNT)
    do
        SPACES="$SPACES "
        echo "$SPACES🦆"
        sleep $SLEEPTIME
    done
    
    for i in $( seq 0 $SPACECOUNT)
    do
        SPACES=${SPACES%?}
        echo "$SPACES🦆"
        sleep $SLEEPTIME
    done
done

