#!/bin/bash

MENU=$( echo -e "Lock\nSleep\nLogout\nReboot\nShutdown\nHibernate" | rofi -dmenu )
case "$MENU" in
    *Lock) i3lock-fancy ;;
    *Sleep) i3lock-fancy && systemctl suspend ;;
    *Logout) i3-msg exit;;
    *Reboot) systemctl reboot ;;
    *Shutdown) systemctl -i poweroff ;;
    *Hibernate) systemctl hibernate ;;
esac
