#!/bin/bash

MENU="$(echo "Lock|Logout|Reboot|Shutdown|" | rofi -dmenu -sep "|")"
case "$MENU" in
    *Lock) i3lock-fancy ;;
    *Logout) i3-msg exit;;
    *Reboot) systemctl reboot ;;
    *Shutdown) systemctl -i poweroff
esac
