#!/bin/bash

#########################################################
#Script Name	: sysmenu
#Description	: Displays power options in a rofi-dmenu.
#Args           : None
#Author       	: Luk Schwalb
#Email         	: schwalb@luk.im
#########################################################
MENU=$( echo -e "Lock\nSleep\nLogout\nReboot\nShutdown\nHibernate" | rofi -dmenu )
case "$MENU" in
    *Lock) i3lock-fancy ;;
    *Sleep) i3lock-fancy && systemctl suspend ;;
    *Logout) i3-msg exit;;
    *Reboot) systemctl reboot ;;
    *Shutdown) systemctl -i poweroff ;;
    *Hibernate) systemctl hibernate ;;
esac
