#!/bin/bash

CONFIG_PATH=$REPOSITORY_DIRECTORY/cryptostorm_client_configuration_files/ecc
VPNS=$( find $CONFIG_PATH/*.ovpn -printf "%f|")
VPN=$(echo "$VPNS" | rofi -dmenu -sep "|")

if [ ! -z $VPN ];
then
    eval "$TERMINAL -e openvpn $CONFIG_PATH/$VPN"
fi
